import os
import json
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "")

def generate_loan_report(loan_type: str, valuation_data: dict) -> str:
    """
    Calls Groq API to generate a detailed Markdown loan evaluation report.
    """
    if not GROQ_API_KEY:
        return f"# Error\n\nGroq API key not found. Please set GROQ_API_KEY in your .env file.\n\nRaw Data:\n{json.dumps(valuation_data, indent=2)}"
        
    client = Groq(api_key=GROQ_API_KEY)
    
    if loan_type == "Home Loan":
        prompt = f"""
You are AegisCR, an enterprise-grade AI Loan Underwriting Engine.
Generate a highly professional, beautifully formatted, concise PDF Property Appraisal & Asset Evaluation Report for a {loan_type}.

The user specifically requested this report to be SHORT, CLEAR, and fit within 1-2 pages max. Be punchy and data-driven. Do not use filler words.
CRITICAL INSTRUCTION: DO NOT INCLUDE ANY APPLICANT PERSONAL OR FINANCIAL INFORMATION (No names, no income, no credit scores). Focus ENTIRELY on the Property, its Valuation, and its Asset-backed Loan Eligibility.

LIVE DATA:
{json.dumps(valuation_data, indent=2)}

You MUST output exactly 6 consolidated sections in Markdown.

CRITICAL STYLING INSTRUCTIONS (READ CAREFULLY):
- Use standard markdown headers (`#`, `##`).
- Use Markdown tables for metrics side-by-side to save vertical space.
- Wrap critical decisions in HTML badges: `<span style="background-color: #10B981; color: white; padding: 4px 8px; border-radius: 4px; font-weight: bold;">ELIGIBLE</span>` (Use #EF4444 for High Risk).
- DO NOT use Unicode or ASCII block characters (like █ or ░) for progress bars.
- DO NOT use the Rupee symbol (₹) anywhere in the report, as it corrupts the PDF encoding. Use `Rs.` instead for all monetary values.
- Instead, for ANY progress/risk bar, you MUST use this exact HTML structure:
  `<div style="width: 150px; background-color: #e2e8f0; border-radius: 4px; height: 14px;"><div style="width: [PERCENTAGE]%; background-color: #ef4444; height: 14px; border-radius: 4px;"></div></div>` (Change width % based on the risk score).
- NEVER output generic introductory text. START IMMEDIATELY with the Header.

STRUCTURE REQUIRED:
1. EXECUTIVE PROPERTY SUMMARY (Highlight Govt Guidance Value, AI Estimated Market Value, Location Score, Market Trend YOY, and the Asset Status as a MASSIVE colored HTML badge).
2. ASSET VALUATION & PROJECTIONS (Use a Markdown table. Show Land Value, Building Value, Total Valuation, and the Future Collateral Appreciation Forecast: 1yr, 3yr, 5yr).
3. ASSET LOAN ELIGIBILITY (Use a single Markdown table. Show Max Eligible Loan, Maximum LTV %, and the Recommended Sanction amount based strictly on the property).
4. NEARBY SIMILAR REGISTERED PROPERTIES (Display the `nearby_properties` array as a clean Markdown table with Survey Num, Distance, Price, Source, and Date).
5. AI ASSET RISK ANALYSIS (Use a table. Show Property Risk, Location Risk, and Fraud Risk using the requested HTML DIV progress bars. List Fraud Detection status).
6. AI APPRAISAL RATIONALE (One short, punchy paragraph explaining the asset valuation rationale and why this property is a good/bad collateral).
"""
    else:
        prompt = f"""
You are AegisCR, an enterprise-grade AI Loan Underwriting and Collateral Appraisal Engine.
Generate a highly professional, detailed, and structured Loan Evaluation Report for a {loan_type}.

Here is the structured appraisal and underwriting data for the asset/applicant:
{json.dumps(valuation_data, indent=2)}

Format the report in Markdown. Include the following sections:
1. Executive Summary & AI Recommendation
2. Asset & Collateral Valuation Details
3. Risk Analysis (Credit, Market, Fraud, Insurance)
4. Final Underwriting Metrics (LTV, EMI, Sanction Amount)

Make it look like an official, automated banking document generated by an AI underwriting system.
Be concise but thorough. Do not include introductory conversational text (e.g. "Here is the report...").
"""
    
    try:
        completion = client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[
                {"role": "system", "content": "You are an AI Underwriting Engine for a top-tier bank."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.2,
            max_tokens=4000,
            top_p=1,
            stream=False,
            stop=None,
        )
        return completion.choices[0].message.content
    except Exception as e:
        return f"# Report Generation Failed\n\nAn error occurred while calling the Groq API:\n{str(e)}\n\nRaw Data:\n{json.dumps(valuation_data, indent=2)}"

def md_to_pdf_bytes(md_text: str) -> bytes:
    """
    Converts markdown text to PDF bytes using xhtml2pdf.
    """
    try:
        import markdown
        from xhtml2pdf import pisa
        from io import BytesIO
    except ImportError:
        return b"Error: markdown and xhtml2pdf libraries are required for PDF conversion."
        
    # Convert markdown to HTML
    html_content = markdown.markdown(md_text, extensions=['tables'])
    
    # Wrap in basic HTML structure with simple CSS
    full_html = f"""
    <html>
    <head>
    <style>
        @page {{ size: A4; margin: 1.5cm 2cm; }}
        body {{ font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; font-size: 10pt; color: #1e293b; line-height: 1.6; }}
        
        /* Typography */
        h1 {{ color: #0f172a; border-bottom: 3px solid #2563eb; padding-bottom: 8px; font-size: 22pt; font-weight: bold; margin-bottom: 25px; text-align: center; }}
        h2 {{ color: #1e40af; border-bottom: 1px solid #cbd5e1; margin-top: 30px; padding-bottom: 5px; font-size: 16pt; font-weight: bold; }}
        h3 {{ color: #334155; font-size: 13pt; margin-top: 20px; font-weight: bold; }}
        p {{ margin-bottom: 12px; }}
        
        /* Lists */
        ul, ol {{ margin-top: 5px; margin-bottom: 15px; padding-left: 20px; }}
        li {{ margin-bottom: 6px; }}
        
        /* Tables */
        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 9.5pt; }}
        th, td {{ border: 1px solid #e2e8f0; padding: 10px 12px; text-align: left; }}
        th {{ background-color: #f8fafc; color: #475569; font-weight: bold; text-transform: uppercase; font-size: 8.5pt; letter-spacing: 0.5px; }}
        tr:nth-child(even) {{ background-color: #fdfdfd; }}
        
        /* Highlights & Badges */
        strong {{ color: #0f172a; font-weight: bold; }}
        .badge {{ display: inline-block; padding: 4px 8px; border-radius: 4px; font-size: 9pt; font-weight: bold; color: white; }}
        
        /* Custom Footer / Watermark logic could go here */
    </style>
    </head>
    <body>
    {html_content}
    </body>
    </html>
    """
    
    result = BytesIO()
    pisa_status = pisa.pisaDocument(BytesIO(full_html.encode("UTF-8")), result)
    
    if pisa_status.err:
        return b"Error generating PDF from Markdown."
    return result.getvalue()
