services:
  - type: web
    name: aegiscr-portal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: UNSPLASH_ACCESS_KEY
        value: zRFlykNbtqwtGbs5CPWvvGRLxNK9xOmQwBsQ4X1Io1Q
      - key: PEXELS_API_KEY
        value: TI15nFTnkzqWP0UAUGuAtLJcFM4PLkLV0JBwVb2KMorQDfk4RGYNIt60
